server:
  port: 8082
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/data-collect?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  # 排除自动配置内
  #autoconfigure:
    #exclude: org.springframework.boot.autoconfigure.aop.AopAutoConfiguration


# MyBatis-plus Configuration
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml # 配置mapper xml文件的路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # mybatis日志

security:
  jwt:
    secretKey: whatever