server:
  port: 8081
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/data-collect?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 排除自动配置内
  #autoconfigure:
    #exclude: org.springframework.boot.autoconfigure.aop.AopAutoConfiguration

  redis:
    # 链接地址
    url: 192.168.1.204
    # 用户名称
    username:
    # 密码
    password:
    # 端口
    port: 6379
    # 连接超时(毫秒)
    timeout: 30000



# MyBatis-plus Configuration
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml # 配置mapper xml文件的路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # mybatis日志

security:
  jwt:
    secretKey: whatever