  redis:
    # 链接地址
    url: 192.168.1.204
    # 用户名称
    username:
    # 密码
    password:
    # 端口
    port: 6379
    # 连接超时(毫秒)
    timeout: 30000
    pool:
      # 连接池最大连接数(使用负值表示没有限制)
      max-active: 8
      # 连接池最大阻塞等待时间
      max-wait: -1
      # 连接池最大空闲连接
      max-idle: 8
      # 连接池最小空闲连接
      min-idle: 0



